name: workflow.yml
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'Dockerfile'
      - '.github/workflows/workflow.yml'
      - 'src/main/java/com/example/fooddelivery/food-delivery-spa/**'

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: backend
            context: .
            dockerfile: Dockerfile
          - image: frontend
            context: ./src/main/java/com/example/fooddelivery/food-delivery-spa
            dockerfile: ./src/main/java/com/example/fooddelivery/food-delivery-spa/Dockerfile

    steps:
      - name: copy-repo
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test --no-daemon

      - name: build
        uses: docker/setup-buildx-action@v3

      - name: qemu
        uses: docker/setup-qemu-action@v3

      - name: login to dockerHub
        uses: docker/login-action@v3
        with:
          username: fleccy
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build + push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            fleccy/${{ matrix.image }}:latest
            fleccy/${{ matrix.image }}:${{ github.sha }}